# Generated by Django 5.2.7 on 2025-10-30 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subcribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('locations', models.ManyToManyField(to='WindScribe.location')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv_4_ext', models.GenericIPAddressField(blank=True, default=None, null=True, unique=True)),
                ('price_per_mounth_4_ext', models.FloatField(default=0)),
                ('ipv_4_local', models.GenericIPAddressField(blank=True, default=None, null=True, unique=True)),
                ('price_per_mounth_4_local', models.FloatField(default=0)),
                ('ipv_6', models.GenericIPAddressField(blank=True, default=None, null=True, unique=True)),
                ('price_per_mounth_6', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WindScribe.subcribe')),
            ],
        ),
    ]
