# Generated by Django 5.2.8 on 2025-12-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindScribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcribe',
            name='Services',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subcribe',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
