# Generated by Django 5.2.8 on 2025-12-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WindScribe', '0002_subcribe_services_alter_subcribe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcribe',
            old_name='Services',
            new_name='services',
        ),
    ]
